title: somuSan Blog
description: I'm just regular everyday normal mofo

url: http://somu5an.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
#   github: accounting101
  twitter: somu5an
#   facebook: bananaqpodcast
  email: somusan997@gmail.com
#   linkedin: reynanteabadiez

google_analytics: "G-1KFQ5X7BHG"

disqus:
  shortname: https-somu5an-github-io

